name: 部署

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   uses: pnpm/action-setup@v3
                with:
                    version: latest
                    run_install: true

            -   run: pnpm run build
            -   run: pnpm run check

            -   uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: dist