name: 发布

on:
    push:
        tags:
            - '**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: latest
                  run_install: true

            - run: pnpm run build
            - run: pnpm run check

            - run: cd dist && zip -q -r -9 ../dist.zip .

            - uses: softprops/action-gh-release@v2
              with:
                  files: dist.zip
                  token: ${{ secrets.GITHUB_TOKEN }}