name: 发布

on:
    push:
        tags:
            - "**"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: latest
                  run_install: true

            - run: pnpm run build
            - run: pnpm run check

            - shell: bash
              run: |
                  sudo apt-get update -y
                  sudo apt-get install hashdeep -y

            - shell: bash
              run: |
                  sha256deep -r -l ./dist > hash.sha256
                  cd dist
                  mv ../hash.sha256 .
                  zip -q -r -9 ../dist.zip .

            - uses: softprops/action-gh-release@v2
              with:
                  files: dist.zip
                  token: ${{ secrets.GITHUB_TOKEN }}
